package post.balling

mods.jei.ingredient.removeAndHide(item('appliedenergistics2:creative_energy_cell'))
mods.jei.ingredient.removeAndHide(item('appliedenergistics2:creative_storage_cell'))
mods.jei.ingredient.removeAndHide(item('buildinggadgets:constructionpastecontainercreative'))
mods.jei.ingredient.removeAndHide(item('draconicevolution:creative_rf_source'))
mods.jei.ingredient.removeAndHide(item('draconicevolution:draconium_capacitor', 2))
mods.jei.ingredient.removeAndHide(item('enderio:block_decoration2', 4))
mods.jei.ingredient.removeAndHide(item('extrautils2:passivegenerator', 6))
mods.jei.ingredient.removeAndHide(item('extrautils2:drum', 4))
mods.jei.ingredient.removeAndHide(item('extrautils2:spike_creative'))
mods.jei.ingredient.removeAndHide(item('extrautils2:creativeenergy'))
mods.jei.ingredient.removeAndHide(metaitem('data_access_hatch.creative'))
mods.jei.ingredient.removeAndHide(metaitem('infinite_energy'))
mods.jei.ingredient.removeAndHide(metaitem('creative_chest'))
mods.jei.ingredient.removeAndHide(metaitem('creative_tank'))
mods.jei.ingredient.removeAndHide(item('simplyjetpacks:itemjetpack'))
mods.jei.ingredient.removeAndHide(item('storagedrawers:upgrade_creative'))
mods.jei.ingredient.removeAndHide(item('storagedrawers:upgrade_creative', 1))
mods.jei.ingredient.removeAndHide(item('thermalcultivation:watering_can', 32000))
mods.jei.ingredient.removeAndHide(item('thermalexpansion:capacitor', 32000))
mods.jei.ingredient.removeAndHide(item('thermalinnovation:drill', 32000))
mods.jei.ingredient.removeAndHide(item('thermalinnovation:magnet', 32000))
mods.jei.ingredient.removeAndHide(item('libvulpes:creativepowerbattery'))

mods.jei.ingredient.removeAndHide(item('enderio:block_zombie_generator'))
mods.jei.ingredient.removeAndHide(item('enderio:block_franken_zombie_generator'))
mods.jei.ingredient.removeAndHide(item('enderio:block_ender_generator'))
