#Splash screen properties
#Thu Apr 02 19:19:54 CEST 2026
background=0xe89089
memoryGood=0x44aa11
font=0x0
barBackground=0xd7d7d7
barBorder=0x1a1a1a
memoryLow=0xE42F2F
rotate=false
memoryWarn=0xE6E84A
showMemory=true
bar=0xae1633
enabled=true
resourcePackPath=resources
logoOffset=0
forgeTexture=fml\:textures/gui/forge.png
fontTexture=textures/font/ascii.png
